global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # If your backend exposes /metrics (e.g., prometheus-net for ASP.NET)
  - job_name: "backend-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8080"]

  # Example for SQL exporter (optional, if you add one later)
  # - job_name: "sqlserver"
  #   static_configs:
  #     - targets: ["sql-exporter:9187"]
